### ISSUE TITLE
[Feature] Create Generic Snackbar/Toast for Flood 

### ISSUE THREAD

**Issue by Ashish-AI** [CCExtractor/Flood_Mobile#38] opened 2021-10-13 05:58 UTC
**Is your feature request related to a problem? Please describe.**
Its an enhancement giving a notch to our product 

**Describe the solution you'd like**
We would have a Generic class that can be used both as a toast and snackbar covering different scenarios such as
```
Caution 
Fail
Success
Information
```
```It can come with or without CTA, completely depends upon our requirement.``` 

**Are you working on this? (Yes/No)**
Yes

**Comment by pratikbaid3** [comment] 2021-10-13 06:09
@Ashish-AI I believe there is already a issue created for the toast that I have assigned you.

**Comment by pratikbaid3** [comment] 2021-10-13 06:33
Let's keep all the component creating and integration in the issue that has already been assigned, since the only way for me to be able to test the components would be after implementation. 

Moreover, this issue has the toast segment to it, which isn't covered in the other issue. So if you want, please propose a solution/implementation on how the toast could be improved (a screenshot maybe) and we could create a seperate issue just for that.

**Comment by pratikbaid3** [comment] 2021-10-13 06:41
You can use the slack button in the readme of this project.

**Comment by pratikbaid3** [comment] 2021-10-13 08:17
Closing as it is a duplicate of #30

**Closed by pratikbaid3** 2021-10-13 08:17 UTC
Labels: duplicate
