### ISSUE TITLE
Newer version of the Kotlin Gradle plugin required

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/Flood_Mobile#64] opened 2022-02-05 19:53 UTC
**Describe the bug**
Newer version of the Kotlin Gradle plugin required. After issue #63 is fixed, further these errors exist.

**To Reproduce**

1. flutter upgrade
2. Run main.dart
3. See error

**Expected behavior**
No errors should occur

**Screenshots**

<img width="745" alt="Screenshot 2022-02-06 at 1 21 54 AM" src="https://user-images.githubusercontent.com/69353350/152656804-d0d481cb-f3eb-4a7f-b23e-a4339d78999b.png">

**Are you working on this issue? (Yes/No)**
Yes

**Comment by pratikbaid3** [comment] 2022-02-16 05:58
Duplicate of #65

**Closed by pratikbaid3** 2022-02-16 05:58 UTC

**Comment by ItsAdityaKSingh** [comment] 2022-02-16 19:10
It was just the successive error which resulted after solving issue #63. Though solved both of them in PR #65 :)
