### ISSUE TITLE
Gesture detector in sidebar

### ISSUE THREAD

**Issue by devmrfitz** [CCExtractor/Flood_Mobile#66] opened 2022-02-10 04:51 UTC
**Is your feature request related to a problem? Please describe.**
The left sidebar can be opened by a left-to-right swipe on the left edge of the screen, which is nice. However, once the sidebar opens, if we want to swipe to close the sidebar, we need to start from almost the extreme right of the screen (red arrow). Since the sidebar doesn't seem to have a gesture detector, a right-to-left swipe (blue arrow) on the same does nothing. This makes the swiping behaviour really inconvenient for single-handed use of large phones.
![image](https://user-images.githubusercontent.com/58381523/153339335-f401a853-ae11-4939-b5b6-b95317efceb4.png)

**Describe the solution you'd like**
Try to implement a gesture detector in the sidebar also so that the blue swipe also works.

**Are you working on this?**
Yes

**Comment by devmrfitz** [comment] 2022-02-10 04:53
@pratikbaid3 Does this look like an acceptable feature request?

**Comment by pratikbaid3** [comment] 2022-02-16 05:52
@devmrfitz The issue you described is actually the intended behavior of the sliding menu drawer. I am not sure if this is actually a problem.

**Comment by devmrfitz** [comment] 2022-02-16 06:20
Alright, I understand. It's just that it gets very difficult to perform the closing swipe on large phone screens

**Comment by adilwahla** [comment] 2023-04-04 19:13
@Akshatji800 Sir assign this to me I will fix this shortly

**Closed** 2023-05-27 19:29 UTC
